### ISSUE TITLE
Signal optimization not working properly

### ISSUE THREAD

**Issue by xdev1** [zouloux/reflex#8]
I made a little test how a Preact component behaves if you use both signal `count` and `count.value` in the same component.
Then I tried the same with Reflex and saw that Reflex has a bug in the signal optimization.

Please have a look at the following demo - both buttons should behave the same, but the Reflex button is not working properly:
https://codesandbox.io/s/rough-meadow-5piocu?file=/src/index.ts

**Comment by zouloux** [comment]
It's patched. Thanks !
https://codesandbox.io/s/focused-goldstine-h1s6dw?file=/src/index.ts
